name: "tausq_log_massall"
max_q: 0
models_to_plot: ["WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque","WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque"]
output_filebase: "tausq_log_massall"
mass_limits: [0.05,1.35]
zoom_ymax: null
include_blends: !!bool false
include_lit: !!bool true
period_scale: "log"
to_plot: !!bool true
overwrite: !!bool true
init_types: ["tophat", "tophat", "tophat", "kde", "kde", "kde"]
