name: "tausq_linear_masshigh"
max_q: 0
models: ["UpSco_Mattea2015","UpSco_Mattea2022","UpSco_ZeroTorque","WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque"]
output_filebase: "tausq_linear_masshigh"
mass_limits: [0.65,1.35]
zoom_ymax: 1400
include_blends: !!bool false
include_lit: !!bool true
period_scale: "linear"
to_plot: !!bool true
overwrite: !!bool false
