name: "tausq_linear_masslow"
max_q: 0
models: ["WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque","WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque"]
output_filebase: "tausq_linear_masslow"
mass_limits: [0.05,0.65]
zoom_ymax: 1800
include_blends: !!bool true
include_lit: !!bool false
period_scale: "linear"
to_plot: !!bool true
overwrite: !!bool true
init_types: ["tophat", "tophat", "tophat", "kde", "kde", "kde"]