name: tausq-test
max_q: 0
models: ["UpSco_Mattea2015","UpSco_Mattea2022","UpSco_ZeroTorque"]
# ,"WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque"]
output_filebase: "test_tausq_"
mass_limits: [0.05,0.65]
zoom_ymax: 2000
include_blends: !!bool true
include_lit: !!bool false
period_scale: "linear"
to_plot: !!bool true
overwrite: !!bool true
