name: "tausq_linear_massall"
max_q: 0
models: ["WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque","WideHat8Myr_Mattea2015","WideHat8Myr_Mattea2022","WideHat8Myr_ZeroTorque"]
output_filebase: "tausq_linear_massall"
mass_limits: [0.05,1.35]
zoom_ymax: null
include_blends: !!bool true
include_lit: !!bool false
period_scale: "linear"
to_plot: !!bool true
overwrite: !!bool false
init_type: ["tophat", "tophat", "tophat", "kde", "kde", "kde"]